# Generated by Django 3.2.3 on 2021-06-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('titulo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Titulo atencion')),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha atencion')),
                ('tipo_vehiculo', models.CharField(max_length=50, verbose_name='Tipo vehiculo atencion')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca atencion')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo atencion')),
                ('tipo_atencion', models.CharField(max_length=50, verbose_name='Tipo atencion atencion')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion atencion')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Email contacto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre contacto')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular contacto')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto contacto')),
                ('mensaje', models.CharField(max_length=50, verbose_name='Mensaje contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Rut trabajador')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre trabajador')),
                ('email', models.CharField(max_length=50, verbose_name='Email trabajador')),
                ('contra', models.CharField(max_length=50, verbose_name='Contra trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Email usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre usuario')),
                ('contrasenha', models.CharField(max_length=25, verbose_name='Contraseña usuario')),
            ],
        ),
    ]
