# Generated by Django 3.2.3 on 2021-06-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='rut',
        ),
        migrations.AlterField(
            model_name='atencion',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca atencion'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo atencion'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Email trabajador'),
        ),
    ]
