# Generated by Django 3.2.3 on 2021-06-24 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210622_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trabajador'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
